/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * carteciano.java
 *
 * Created on 15/09/2011, 02:52:27 PM
 */

package plot;

import java.awt.Color;
import java.awt.Graphics;



/**
 *
 * @author rick
 */
public class carteciano extends javax.swing.JPanel {


    private javax.swing.JLabel jLabel1;

    /** Creates new form carteciano */
    public carteciano() {
        initComponents();
        this.setSize(1024,700);


    }
    @Override
    public void paintComponent(Graphics g){
        super.paintComponent(g);
        System.out.println("paintcomponent");
        int x2 = this.getWidth()/2;
        int y2 = this.getHeight()/2;
        System.out.println("se dibuja");
        g.setColor(Color.red);
        g.drawLine(100, 100, getSize().width-1, getSize().height-1);
        g.fillRect(0, 0, getSize().width - 30, getSize().height - 30);
        g.drawLine(0, x2, x2, 400);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(288, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(37, 37, 37))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addContainerGap(275, Short.MAX_VALUE))
        );
    }




}
